update xxpck_entities 
 set upload_string = 'cp &DATAFILE "$TEMP_DIR/&TEMPLATE_FILE"; $XXPCK_TOP/bin/XMLPubTemplateFileImp.sh $DB_USER $DB_PWD "&TEMPLATE_CODE" "&APPLICATION_SHORT_NAME" "&TEMPLATE_LANGUAGE" "&TEMPLATE_TERRITORY" "&TEMPLATE_TYPE" "$TEMP_DIR/&TEMPLATE_FILE"; CONCSUB $DB_USER/$DB_PWD SYSADMIN 'System Administrator' SYSADMIN WAIT=Y CONCURRENT  XXPCK  XXPCK_XDOTMGEN "OUTDATED"; $XXPCK_TOP/bin/xxpck_update_xdo_lobs.sh "&APPLICATION_SHORT_NAME"  "&TEMPLATE_CODE"'
 where entity_name = 'XDO_TEMPLATE_FILE' 
commit;
