#!/bin/ksh
# $Id: XMLPubTemplateFileImp.sh 1388 2011-08-01 15:00:29Z mshapira $
# Copyright Unitask Inc., 1999-2010. All rights reserved
INSTALL_DIR=`pwd`
#export CLASSPATH=$CLASSPATH:$XXPCK_TOP/xdk/lib/xsu12.jar:$XXPCK_TOP/xdk/lib/xmlparserv2.jar
 
DB_USER=$1
APPS_PWD=$2
TEMPLATE_CODE=$3
APPLICATION_SHORT_NAME=$4
TEMPLATE_LANGUAGE=$5
TEMPLATE_TERRITORY=$6
TEMPLATE_TYPE=$7
FILE_NAME=$8

CLASSPATH=$ORIG_CLASSPATH
echo $CLASSPATH
#env > /tmp/xxpck_before.log
#source /home/oracle/EBSapps.env run
#env > /tmp/xxpck_after.log
#echo "$XXPCK_DB_HOST:$XXPCK_DB_PORT:$TWO_TASK"

$JAVA_JRE -mx512m  oracle.apps.xdo.oa.util.XDOLoader UPLOAD -DB_USERNAME $DB_USER -DB_PASSWORD $DB_PWD -JDBC_CONNECTION "$XXPCK_DB_HOST:$XXPCK_DB_PORT:$TWO_TASK" -LOB_TYPE TEMPLATE -APPS_SHORT_NAME $APPLICATION_SHORT_NAME -LOB_CODE "$TEMPLATE_CODE" -LANGUAGE $TEMPLATE_LANGUAGE -TERRITORY $TEMPLATE_TERRITORY -CUSTOM_MODE FORCE -XDO_FILE_TYPE $TEMPLATE_TYPE -FILE_NAME $FILE_NAME 

if [ $? -ne 0 ]
then
   exit 1
fi

